const carrierFormTemplate = (data) => {
  return `
<!DOCTYPE html>
<html lang="en">

<head>
<meta charset="UTF-8" />

<style>

*{
    margin:0;
    padding:0;
    box-sizing:border-box;
    font-family:Arial, Helvetica, sans-serif;
}

body{
    padding:40px;
    color:#222;
    background:#fff;
}

.header{
    text-align:center;
    border-bottom:3px solid #1a1a4d;
    padding-bottom:20px;
    margin-bottom:35px;
}

.header h1{
    color:#1a1a4d;
    font-size:30px;
    margin-bottom:8px;
}

.header h2{
    color:#ff1493;
    font-size:20px;
    font-weight:600;
}

.header p{
    color:#666;
    margin-top:10px;
    font-size:14px;
}

.section-title{
    background:#1a1a4d;
    color:#fff;
    padding:12px 16px;
    border-radius:6px;
    font-size:18px;
    margin-bottom:20px;
}

.table{
    width:100%;
    border-collapse:collapse;
}

.table tr{
    border-bottom:1px solid #ddd;
}

.table td{
    padding:14px 10px;
    font-size:15px;
}

.label{
    width:35%;
    font-weight:bold;
    background:#f8f8f8;
}

.value{
    color:#333;
}

.footer{
    margin-top:60px;
    text-align:center;
    font-size:13px;
    color:#777;
    border-top:1px solid #ddd;
    padding-top:20px;
}

</style>

</head>

<body>

<div class="header">

<h1>Slee Street Logistics LLC</h1>

<h2>Carrier Application Form</h2>

<p>
New Carrier Application Submission
</p>

</div>

<div class="section-title">

Carrier Information

</div>

<table class="table">

<tr>
<td class="label">Business Legal Name</td>
<td class="value">${data.businessLegalName || "-"}</td>
</tr>

<tr>
<td class="label">First Name</td>
<td class="value">${data.firstName || "-"}</td>
</tr>

<tr>
<td class="label">Last Name</td>
<td class="value">${data.lastName || "-"}</td>
</tr>

<tr>
<td class="label">Phone Number</td>
<td class="value">${data.phoneNumber || "-"}</td>
</tr>

<tr>
<td class="label">Email Address</td>
<td class="value">${data.email || "-"}</td>
</tr>

<tr>
<td class="label">Carrier Mobile Provider</td>
<td class="value">${data.carrierMobile || "-"}</td>
</tr>

<tr>
<td class="label">Equipment Type</td>
<td class="value">${data.equipmentType || "-"}</td>
</tr>

<tr>
<td class="label">ZIP Code</td>
<td class="value">${data.zipCode || "-"}</td>
</tr>

<tr>
<td class="label">Submission Date</td>
<td class="value">
${new Date(data.submittedAt || Date.now()).toLocaleString()}
</td>
</tr>

</table>

<div class="footer">

<p>
This document was automatically generated by Slee Street Logistics LLC.
</p>

<p style="margin-top:8px;">
© ${new Date().getFullYear()} Slee Street Logistics LLC. All Rights Reserved.
</p>

</div>

</body>

</html>
`;
};

export default carrierFormTemplate;